from .base_exception import BaseException


class RecordNotFoundError(BaseException):
    pass
